### PR TITLE
Introduce link checker

### PR DESCRIPTION
**Pull request by asmacdo**

### CODE REVIEW

**Comment by yarikoptic** [comment]
I do not see such exact wording there. Made you admin so hopefully you could get to that interface yourself, can you?

**Comment by asmacdo** [comment]
I opened another PR from non-fork and suddenly this one started working :shrug:

**Comment by asmacdo** [comment]
@yarikoptic AFAICT there is no way to get the linkchecker to ignore Tor's malformed email address. (which looks malformed deliberately to avoid spam). 

Even when we --ignore-url, it still checks the syntax and fails. 

Option 1: fix email addr
Option 2: remove email address button
Option 3: try another tool

**Comment by yarikoptic** [comment]
Could you check/ file ticket for link checker?

**Comment by asmacdo** [comment]
https://github.com/linkchecker/linkchecker/issues/848

**Comment by asmacdo** [comment]
@yarikoptic got it. ready for review

**Comment by yarikoptic** [comment]
Great, thank you! I will deploy later

**Pull request merged**
