### PR TITLE
Check external links

### PR DESCRIPTION
**Pull request by asmacdo**
Wasn't as simple as adding `--check-extern` to the invocation.

The link checker treats some internal links as external,
    and treats those relative paths as absolote, resulting errors, ie:

```
URL        `/theme/img/3rd/registry_logo.svg'
Name       `DataLad-Registry'
Parent URL file:///home/austin/devel/centerforopenneuroscience.org/output/projects.html, line 153, col 9
Real URL   file:///theme/img/3rd/registry_logo.svg
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/theme/img/3rd/registry_logo.svg'>
```

I'm getting some errors locally, pushing here to see if we get the same results.

### CODE REVIEW

**Comment by asmacdo** [comment]
## TODO/error list:

- [ ] URL        `http://nipy.bic.berkeley.edu/waterfall'
Name       `cover up a\n  wide variety of associated projects'
Parent URL http://localhost:8000/projects, line 577, col 7
Real URL   http://nipy.bic.berkeley.edu/waterfall
Check time 60.246 seconds
Result     Error: ConnectTimeout: HTTPConnectionPool(host='nipy.bic.berkeley.edu', port=80): Max retries exceeded with url: /robots.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f575ad5be10>, 'Connection to nipy.bic.berke...

- [ ] URL        `http://nipy.org/dipy'
Name       `Dipy'
Parent URL http://localhost:8000/projects, line 579, col 11
Real URL   https://nipy.org/dipy
Check time 0.182 seconds
Size       5KB
Warning    [http-redirected] Redirected to
           `https://nipy.org/dipy' status: 301 Moved Permanently.
Result     Error: 404 Not Found

- [ ] URL        `https://profiles.umassmed.edu/display/130002'
Name       `Research Page'
Parent URL http://localhost:8000/whoweare, line 223, col 9
Real URL   https://profiles.umassmed.edu/display/130002
Check time 0.370 seconds
Result     Error: SSLError: HTTPSConnectionPool(host='profiles.umassmed.edu', port=443): Max retries exceeded with url: /display/130002 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get...

- [ ] URL        `https://static1.squarespace.com/static/57e18d24d482e96cd836c9f1/t/57ed5dabff7c506a4793d0f3/1475173803590/JRM_CV.pdf'
Name       `CV'
Parent URL http://localhost:8000/whoweare, line 346, col 7
Real URL   https://static1.squarespace.com/static/57e18d24d482e96cd836c9f1/t/57ed5dabff7c506a4793d0f3/1475173803590/JRM_CV.pdf
Check time 0.227 seconds
Size       21B
Result     Error: 404 Not Found


- [ ] URL        `/theme/img/team/tor.jpg'
Parent URL http://localhost:8000/whoweare, line 396, col 15
Real URL   http://localhost:8000/theme/img/team/tor.jpg
Check time 0.002 seconds
Result     Error: ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

- [ ] URL        `http://mdvoc.me'
Name       `Web Page'
Parent URL http://localhost:8000/whoweare, line 482, col 5
Real URL   http://mdvoc.me
Check time 0.003 seconds
Result     Error: ConnectionError: HTTPConnectionPool(host='mdvoc.me', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f575ad85050>: Failed to resolve 'mdvoc.me' ([Errno -2] Name or s...

- [ ] URL        `https://drive.google.com/file/d/0BzsWya5NQiiEb3p5eWFiSDJqYnM'
Name       `CV'
Parent URL http://localhost:8000/whoweare, line 483, col 5
Real URL   https://drive.google.com/file/d/0BzsWya5NQiiEb3p5eWFiSDJqYnM/edit
Check time 0.658 seconds
Warning    [http-redirected] Redirected to
           `https://drive.google.com/file/d/0BzsWya5NQiiEb3p5eWFiSDJqYnM/'
           status: 302 Moved Temporarily.
           [http-redirected] Redirected to
           `https://drive.google.com/file/d/0BzsWya5NQiiEb3p5eWFiSDJqYnM/edit'
           status: 302 Moved Temporarily.
Result     Error: 401 Unauthorized

- [ ] URL        `http://www5.unitn.it/People/en/Web/Persona/PER0120101'
Name       `Research Page'
Parent URL http://localhost:8000/whoweare, line 518, col 5
Real URL   http://www5.unitn.it/People/en/Web/Persona/PER0120101
Check time 61.799 seconds
Size       162B
Result     Error: ReadTimeout: HTTPSConnectionPool(host='www5.unitn.it', port=443): Read timed out. (read timeout=60)

- [ ] URL        `https://www.researchgate.net/profile/Horea-Christian'
Name       `Research Page'
Parent URL http://localhost:8000/whoweare, line 659, col 4
Real URL   https://www.researchgate.net/profile/Horea-Christian
Check time 0.231 seconds
Result     Error: 403 Forbidden

- [ ] URL        `http://chymera.eu/docs/cv-acad-m.pdf'
Name       `CV'
Parent URL http://localhost:8000/whoweare, line 660, col 4
Real URL   https://chymera.eu/docs/cv-acad-m.pdf
Check time 0.606 seconds
Size       315B
Warning    [http-redirected] Redirected to
           `https://chymera.eu/docs/cv-acad-m.pdf' status: 301
           Moved Permanently.
Result     Error: 404 Not Found

- [ ] URL        `http://nipy.org/dipy/'
Parent URL http://localhost:8000/whoweare, line 686, col 3
Real URL   https://nipy.org/dipy/
Check time 0.100 seconds
Size       5KB
Warning    [http-redirected] Redirected to
           `https://nipy.org/dipy/' status: 301 Moved
           Permanently.
Result     Error: 404 Not Found

- [ ] URL        `http://martinos.org/mne/stable/mne-python.html'
Parent URL http://localhost:8000/whoweare, line 695, col 3
Real URL   https://mne.tools/stable/mne-python.html
Check time 1.464 seconds
Size       5KB
Warning    [http-redirected] Redirected to
           `https://www.nmr.mgh.harvard.edu/mne/stable/mne-python.html'
           status: 302 Found.
           [http-redirected] Redirected to
           `https://mne.tools/stable/mne-python.html' status: 301
           Moved Permanently.
Result     Error: 404 Not Found

- [ ] URL        `http://neuralensemble.org/pynn/'
Parent URL http://localhost:8000/whoweare, line 709, col 3
Real URL   http://neuralensemble.org/pynn/
Check time 0.031 seconds
Size       5KB
Result     Error: 404 Not Found

- [ ] URL        `http://www.ni.tu-berlin.de/software/spykeviewer'
Parent URL http://localhost:8000/whoweare, line 716, col 3
Real URL   https://www.ni.tu-berlin.de/software/spykeviewer/
Check time 1.975 seconds
Size       418B
Warning    [http-redirected] Redirected to
           `https://www.ni.tu-berlin.de/software/spykeviewer'
           status: 301 Moved Permanently.
           [http-redirected] Redirected to
           `http://www.ni.tu-berlin.de/software/spykeviewer/'
           status: 301 Moved Permanently.
           [http-redirected] Redirected to
           `https://www.ni.tu-berlin.de/software/spykeviewer/'
           status: 301 Moved Permanently.
Result     Error: ConnectionError: HTTPConnectionPool(host='opportunity.bv.tu-berlin.de', port=80): Max retries exceeded with url: /software (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f575c0cde50>: Failed to resolve 'oppo...

- [ ] URL        `http://wiki.incf.org/mediawiki/index.php/Neuroimaging_Task_Force'
Parent URL http://localhost:8000/whoweare, line 727, col 5
Real URL   https://www.incf.org/sbp/brain-imaging-data-structure-bidsmediawiki/index.php/Neuroimaging_Task_Force
Check time 1.592 seconds
Warning    [http-redirected] Redirected to
           `https://www.incf.org/sbp/brain-imaging-data-structure-bidsmediawiki/index.php/Neuroimaging_Task_Force'
           status: 301 Moved Permanently.
Result     Error: 404 Not Found

**Comment by yarikoptic** [comment]
thank you!  So should I wait until more addressed ? (best to place checklist into top level description so github would show counter for how many left to resolve)

**Comment by asmacdo** [comment]
@yarikoptic i addressed the ones I could fix easily, feel free to have a go.

I can open issues for any remaining if we want to merge

**Comment by asmacdo** [comment]
I'm checking off as I file issues or solve them.

**Pull request merged**
