### PR TITLE
New variant logos for T-shirts

### PR DESCRIPTION
**Pull request by TheChymera**
@yarikoptic as discussed in the meeting.

### CODE REVIEW

**Comment by yarikoptic** [comment]
which font did you use in the NH one? for me it looks not centered and different from rendered in .png version

**Comment by TheChymera** [comment]
It's “Cinzel”. It is licensed via the Open Font License (GPL equivalent, free copy, distribution, modification, copyleft). You can get it from here https://www.1001fonts.com/cinzel-font.html

**Comment by TheChymera** [comment]
If you want I can add the font in the PR, but it will be a bit confusing since it won't get auto-loaded. I have created a “compiled” version of the SVG, with all text as paths, and renamed the source version accordingly

**Comment by yarikoptic** [comment]
Great. FWIW -- in such cases I few times did -- added a layer with duplicate original text, kept it as text but made invisible.  Then in another layer, visible one, replaced that text with paths.  This way -- renders fine, but if really need to be fixed, could be done in original text, reduplicated, converted to path.

**Comment by TheChymera** [comment]
If you insist I can merge them ofc, but I'd rather have them separate, since a lot of printing services seem to have trouble with invisible layers in the exported PDF confusing their workflow.

**Comment by yarikoptic** [comment]
merge what?  keep separate what?  
I am talking about having text also available as a path while also keeping a layer with original text just in case.

**Comment by TheChymera** [comment]
I meant merge the files, we now have a SVG with text-mode text, and one in which the text is fully converted to paths. Merging them is possible, but if exporting to e.g. PDF, people would always need to remember to delete invisible layers since they can sometimes break processing workflows. This way we have the “compiled” logic, which people can just edit the colors in, which can be imported as a sub-graphic in another vector image etc. without needing to remove anything, and the original image in which the text can be edited.

**Pull request merged**
